markdown: kramdown
safe: false
permalink: /:categories/:title
exclude:
  - README.md
origin: https://plzhai.github.io
name: 饮冰散人

defaults:
  - scope:
        path: blog/_posts
        type: posts
    values:
        permalink: blog/posts/:title
        layout: post
  - scope:
        path: discovery/_posts
    values:
        layout: post

blog:
    name: 饮冰止
    desc: 生活 读书 新知

    category:
        recent: 近日工作
        communicate: 交流分享
        essay: 鹦鹉杂谈
        life: 闲游野记
        
    categories:
      - name:  recent
        title: 近日工作

      - name:  communicate
        title: 交流分享

      - name:  essay
        title: 鹦鹉杂谈

      - name: life
        title: 闲游野记

    scrollingLoadCount: 0

meta:
    author:
        name: Plzhai
        email: plzhai@amss.ac.cn
        disqus: tech-justlog-me                     # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: plzhai                          # GitHub账号
        gravatar: 92030a7ec2265ca9c3e4dba67e3ac21e  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: https://www.google.com/jsapi               # Google API地址
    gravatar: https://en.gravatar.com/avatar/        # Gravatar头像服务器地址
